version: '3'

services:
  app:
    container_name: node-job app
    build: .
    ports:
      - "8080:5000"
    links:
      - mysql-dev
    depends_on:
      - mysql-dev
    restart: always
    command: npm start


  mysql-dev:
    container_name: mysql-container
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobsearch 
    ports:
      - "3306:3306"

    
      frontend:
        container_name: client
      





      