
export const ALL_JOBS= 'ALL_JOBS'
export const ALL_JOBS_SUCCESS = 'ALL_JOBS_SUCCESS' 

export const JOB_BY_ID = 'JOBS_BY_ID'
export const JOB_BY_ID_SUCCESS = 'JOBS_BY_ID_SUCCESS'

export const ADD_JOB = 'ADD_JOB'
export const ADD_JOB_SUCCESS = 'ADD_JOB_SUCCESS'

export const UPDATE_JOB = 'UPDATE_JOB'
export const UPDATE_JOB_SUCCESS = 'UPDATE_JOB_SUCCESS'

export const REMOVE_JOB= 'REMOVE_JOB'
export const REMOVE_JOB_SUCCESS = 'REMOVE_JOB_SUCCESS'

export const ALL_APPLICANTS= 'ALL_APPLICANT'
export const ALL_APPLICANTS_SUCCESS = 'ALL_APPLICANT_SUCCESS' 

export const APPLICANT_BY_ID = 'APPLICANT_BY_ID'
export const APPLICANT_BY_ID_SUCCESS = 'APPLICANT_BY_ID_SUCCESS'

export const ADD_APPLICANT= 'ADD_APPLICANT'
export const ADD_APPLICANT_SUCCESS = 'ADD_APPLICANT_SUCCESS'

export const UPDATE_APPLICANT = 'UPDATE_APPLICANT'
export const UPDATE_APPLICANT_SUCCESS = 'UPDATE_APPLICANT_SUCCESS'

export const ALL_APPLICANT_APPLIED_JOBS ='ALL_APPLICANT_APPLIED_JOBS'
export const ALL_APPLICANT_APPLIED_JOBS_SUCCESS ='ALL_APPLICANT_APPLIED_JOBS_SUCCESS'

export const ALL_APPLICATIONS= 'ALL_APPLICATIONS'
export const ALL_APPLICATIONS_SUCCESS = 'ALL_APPLICATIONS_SUCCESS'

export const APPLICATION_BY_ID = 'APPLICATIONS_BY_ID'
export const APPLICATION_BY_ID_SUCCESS = 'APPLICATIONS_BY_ID_SUCCESS'





export const ALL_RECRUITERS= 'ALL_RECRUITERS'
export const ALL_RECRUITERS_SUCCESS = 'ALL_RECRUITER_SUCCESS' 

export const RECRUITER_BY_ID = 'RECRUITER_BY_ID'
export const RECRUITER_BY_ID_SUCCESS = 'RECRUITER_BY_ID_SUCCESS'

export const ADD_RECRUITER = 'ADD_RECRUITER'
export const ADD_RECRUITER_SUCCESS = 'ADD_RECRUITER_SUCCESS'

export const UPDATE_RECRUITER = 'UPDATE_RECRUITER'
export const UPDATE_RECRUITER_SUCCESS = 'UPDATE_RECRUITER_SUCCESS'

export const REMOVE_RECRUITER= 'REMOVE_RECRUITER'
export const REMOVE_RECRUITER_SUCCESS = 'REMOVE_RECRUITER_SUCCESS'

export const ALL_ADMINS='ALL_ADMIN'
export const ALL_ADMINS_SUCCESS='ALL_ADMIN_SUCCESS'

export const ADMIN_BY_ID = 'ADMIN_BY_ID'
export const ADMIN_BY_ID_SUCCESS = 'ADMIN_BY_ID_SUCCESS'

export const ADD_ADMIN= 'ADD_ADMIN'
export const ADD_ADMIN_SUCCESS = 'ADD_ADMIN_SUCCESS'

export const UPDATE_ADMIN = 'UPDATE_ADMIN'
export const UPDATE_ADMIN_SUCCESS = 'UPDATE_ADMIN_SUCCESS'
